# yaml para creacion de pipeline con plugin bamboo
pipelines:
  pipelineName: 'pipelineBamboo'
  description: 'alguna descripcion'
  projectName: 'TSOFT'
  stages:
    - gatePre: ''
    - stage_1:
        pipelineName: 'pipelineBamboo'
        waitForPlannedStartDate: '0'
        - tasks:
            - nameTask: 'Tarea 1 - Build Plan'
              description: ''
              plugin: 'Bamboo OnPremise'
              customRevision: 'develop'
              planKey: '$[PlanKey]'
              projectKey: 'APIPRDO'
              resultFormat: 'json'
              resultPropertySheet: '/myJob/runResult'
              waitForBuild': '1'
              waitTimeout': '500'
              - pluginConf:
                advancedMode : '0'
                allowOutOfOrderRun : '0'
                alwaysRun : '0'
                enabled : '1'
                errorHandling : 'stopOnError'
                insertRollingDeployManualStep : '0'
                resourceName : 'local'
                skippable : '0'
                stageSummaryParameters : '[{"name":"buildResultKey","label":"buildResultKey"},{"name":"buildUrl","label":"buildUrl"}]'
                subpluginKey : 'EC-Bamboo'
                subprocedure : 'RunPlan'
                taskType : 'PLUGIN'
                useApproverAcl : '0'
                waitForPlannedStartDate : '0'
            - nametask: 'Tarea 2 - Print Build'
              description : ''
              actualParameter : [
                  commandToRun: 'echo "$[/myStageRuntime/tasks["Tarea 0 - Build Plan"]/job/outputParameters/buildResultKey]"'
              ]
              - CommnandConf:
                  advancedMode: '0'
                  allowOutOfOrderRun: '0'
                  alwaysRun: '0'
                  enabled: '1'
                  errorHandling: 'stopOnError'
                  insertRollingDeployManualStep: '0'
                  resourceName: 'local'
                  skippable: '0'
                  subpluginKey: 'EC-Core'
                  subprocedure: 'RunCommand'
                  taskType: 'COMMAND'
                  useApproverAcl: '0'
                  waitForPlannedStartDate: '0'
                  stageSummaryParameters: '[{"name":"buildResultKey","label":"buildResultKey"},{"name":"buildUrl","label":"buildUrl"}]'
    - gatePro:

