version: "3.7"

services:
  cloudbees-server:
    image: cloudbees/cbflow-server:10.1.0.145850_2.1.12_20210224
    ports:
      - "8443:8443"
    volumes:
      - cloudbees-data:/opt/cbflow
    networks:
      cloudbees-net:
    environment:
      - CBF_SERVER_HOST=cloudbees-server
      - CBF_WEB_HOST=cloudbees-web
  cloudbees-database:
    image: mysql:5.7
    networks:
      cloudbees-net:
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=eflow"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
  cloudbees-web:
    image: cloudbees/cbflow-web:10.1.0.145850_2.1.12_20210224
    ports:
      - "2443:2443"
      - "2080:2080"
    networks:
      cloudbees-net:
    environment:
      - CBF_SERVER_HOST=cloudbees-server
      - CBF_WEB_HOST=cloudbees-web

networks:
  cloudbees-net:

volumes:
  mysql-data:
  cloudbees-data:
